### ISSUE TITLE
step1

### ISSUE THREAD

**Issue by YYYYzhuo** [mhdslh/Federated-Learning-in-Unreliable-and-Resource-Constrained-Cellular-Wireless-Networks#1]
Is step 1 missing from your code?

**Comment by mhdslh** [comment]
If I remember correctly, step 1 calculates the uplink success probability using the derived equations from the paper in Matlab, and it's straightforward. I have only uploaded the Python code in this repository. However, if you need the complete code, please send an email to salehi.mohammad71@gmail.com, and I will provide all the codes and results.
